force-app/main/default/objects/Zoom_Phone_Calls_Info__c/Zoom_Phone_Calls_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Phone Calls Info</label>
    <nameField>
        <label>Zoom Phone Calls Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Phone Calls Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Call_Id__c</fullName>
    <description>Unique identifier of the phone call.</description>
    <inlineHelpText>Unique identifier of the phone call.</inlineHelpText>
    <label>Call Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Zoom_Users_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Users_Info__c</fullName>
    <label>Zoom Users Info</label>
    <referenceTo>Zoom_Users_Info__c</referenceTo>
    <relationshipName>Zoom_Phone_Calls_Infos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Available</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Away__c.field-meta.xml
<CustomField>
    <fullName>Away__c</fullName>
    <label>Away</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/CC_Prev_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Prev_Status__c</fullName>
    <label>Prev Status CC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/CC_Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>CC_Status_Updated__c</fullName>
    <label>Status Updated CC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Contact_Center_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Center_Status__c</fullName>
    <description>Contact center user&apos;s availability status.</description>
    <inlineHelpText>Contact center user&apos;s availability status.</inlineHelpText>
    <label>Status CC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Do_Not_Disturb__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Disturb__c</fullName>
    <label>Do Not Disturb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Calendar_Event__c.field-meta.xml
<CustomField>
    <fullName>In_Calendar_Event__c</fullName>
    <label>In Calendar Event</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Meeting__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting__c</fullName>
    <label>In Meeting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Not_Ready__c.field-meta.xml
<CustomField>
    <fullName>Not_Ready__c</fullName>
    <label>Not Ready</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Occupied__c.field-meta.xml
<CustomField>
    <fullName>Occupied__c</fullName>
    <label>Occupied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline__c.field-meta.xml
<CustomField>
    <fullName>Offline__c</fullName>
    <label>Offline</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline_Status__c.field-meta.xml
<CustomField>
    <fullName>Offline_Status__c</fullName>
    <label>Offline Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/On_Phone_Call__c.field-meta.xml
<CustomField>
    <fullName>On_Phone_Call__c</fullName>
    <label>On Phone Call</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <label>Presenting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Ready__c.field-meta.xml
<CustomField>
    <fullName>Ready__c</fullName>
    <label>Ready</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Tracking_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Date__c</fullName>
    <label>Tracking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_Phone_Calls_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Phone_Calls_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Phone Calls Info</label>
    <referenceTo>Zoom_Phone_Calls_Info__c</referenceTo>
    <relationshipLabel>Zoom Users Infos</relationshipLabel>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_User_Id__c</fullName>
    <description>The unique identifier of the user (userId).</description>
    <inlineHelpText>The unique identifier of the user (userId).</inlineHelpText>
    <label>Zoom User Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestClasses/ZoomTestDataFactory.cls
@isTest
public with sharing class ZoomTestDataFactory {
    public static User createUser(String prof, String email) {
        CallCenter cc = [SELECT Id FROM CallCenter LIMIT 1];
        Profile profId = [SELECT Id FROM Profile WHERE Name = :prof LIMIT 1];
        User usr = new User();
        usr.Email = 'testuser' + email;
        usr.Username = 'testuser' + email;
        usr.FirstName = 'Test';
        usr.LastName = 'User';
        usr.Alias = 'tuser';
        usr.TimeZoneSidKey = 'America/Los_Angeles';
        usr.LocaleSidKey = 'en_US';
        usr.EmailEncodingKey = 'UTF-8';
        usr.LanguageLocaleKey = 'en_US';
        usr.isActive = true;
        usr.ProfileId = profId.Id;
        usr.CallCenterId = cc.Id;
        insert usr;
        return usr;
    }

    public static List<User> createListUsers(Integer count, String prof, String email) {
        CallCenter cc = [SELECT Id, name FROM CallCenter LIMIT 1];
        Profile profId = [SELECT Id FROM Profile WHERE Name = :prof LIMIT 1];
        List<User> testUsers = new List<User>();
        for (Integer i = 0; i < count; i++) {
            User usr = new User();
            usr.Email = 'testuser' + i + email;
            usr.Username = 'testuser' + i + email;
            usr.FirstName = 'Test' + i;
            usr.LastName = 'User ' + i;
            usr.Alias = 'tuser' + i;
            usr.TimeZoneSidKey = 'America/Los_Angeles';
            usr.LocaleSidKey = 'en_US';
            usr.EmailEncodingKey = 'UTF-8';
            usr.LanguageLocaleKey = 'en_US';
            usr.isActive = true;
            usr.ProfileId = profId.Id;
            usr.CallCenterId = cc.Id;
            testUsers.add(usr);
        }
        insert testUsers;
        return testUsers;
    }

    public static List<Zoom_Users_Info__c> createListZoomUsersInfo(Integer count, String prof, String email) {
        createListUsers(count, prof, email);
        List<User> usrLst = [SELECT Id, Name, Email FROM User WHERE Email LIKE :'%testuser%'];
        List<Zoom_Users_Info__c> zoomUsersInfo = new List<Zoom_Users_Info__c>();
        List<String> statuses = new List<String>{ 'Available', 'Away', 'In_Calendar_Event', 'In_Meeting', 'Offline', 'On_Phone_Call', 'Presenting', 'Do_Not_Disturb'};
        List<String> ccStatuses = new List<String>{ 'Ready', 'Not Ready', 'Occupied', 'Offline', 'Not Ready', 'Offline', 'Ready', 'Occupied' };
        for (Integer i = 0; i < count; i++) {
            Zoom_Users_Info__c zoomUser = new Zoom_Users_Info__c();
            zoomUser.User__c                    = usrLst[i].Id;
            zoomUser.Email__c                   = usrLst[i].Email;
            zoomUser.Name                       = usrLst[i].Name;
            zoomUser.Zoom_User_Id__c            = 'ukAAkZKfROKMSw1bj_RDFQ';
            zoomUser.Presence_Status__c         = statuses[i];
            zoomUser.Status_Updated__c          = DateTime.now();
            zoomUser.Tracking_Date__c           = Date.today();
            zoomUser.Available__c               = 0;
            zoomUser.Away__c                    = 0;
            zoomUser.In_Calendar_Event__c       = 0;
            zoomUser.In_Meeting__c              = 0;
            zoomUser.Offline__c                 = 0;
            zoomUser.On_Phone_Call__c           = 0;
            zoomUser.Presenting__c              = 0;
            zoomUser.Do_Not_Disturb__c          = 0;

            zoomUser.Contact_Center_Status__c   = ccStatuses[i];
            zoomUser.CC_Prev_Status__c          = i==0 ? ccStatuses[1] : ccStatuses[i-1];
            zoomUser.CC_Status_Updated__c       = DateTime.Now();
            zoomUser.Ready__c                   = 0;
            zoomUser.Not_Ready__c               = 0;
            zoomUser.Occupied__c                = 0;
            zoomUser.Offline_Status__c          = 0;
            zoomUsersInfo.add(zoomUser);
        }
        insert zoomUsersInfo;
        return zoomUsersInfo;
    }

    public static Zoom_Phone_Calls_Info__c createZoomCall(){
        List<Zoom_Users_Info__c> zoomUser = createListZoomUsersInfo(1, 'System Administrator', 'testuser@some.com');
        Zoom_Phone_Calls_Info__c zoomCall = new Zoom_Phone_Calls_Info__c();
        zoomCall.Zoom_Users_Info__c = zoomUser[0].Id;
        zoomCall.Name = 'Test Call';
        zoomCall.Call_Id__c = '123456789';
        insert zoomCall;
        return zoomCall;
    }
}