force-app/main/default/objects/Zoom_Phone_Calls_Info__c/Zoom_Phone_Calls_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Phone Calls Info</label>
    <nameField>
        <label>Zoom Phone Calls Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Phone Calls Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Call_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Call_Date_Time__c</fullName>
    <description>Start time of the call</description>
    <inlineHelpText>Start time of the call</inlineHelpText>
    <label>Call Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Call_Id__c</fullName>
    <description>Unique identifier of the phone call.</description>
    <inlineHelpText>Unique identifier of the phone call.</inlineHelpText>
    <label>Call Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZoomPhone/ZoomUsersPhoneService.cls
public with sharing class ZoomUsersPhoneService {
    public static HttpResponse zoomPhoneCallsCallout(String email){
        String address = 'callout:ZoomPhone/phone/users/' + email + '/call_logs';
 
        // DateTime prev30Mins = DateTime.now().addMinutes(-30);
        DateTime lastHour = DateTime.now().addHours(-1);
        String fromStr = lastHour.formatGMT('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'');
        String toStr = DateTime.now().formatGMT('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'');
        String fromTime = '?from=' + fromStr;
        String toTime = '&to=' + toStr;

        String pageSize = '&page_size=300';
        String url = address + fromTime + toTime + pageSize;

        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setHeader('Content-type', 'application/json');
        req.setEndpoint(url);
        Http http = new Http();
        HttpResponse resopnse = http.send(req);
        return resopnse;
    }



    public static List<Zoom_Phone_Calls_Info__c> checkDuplicatePhoneCalls(Map<String, Zoom_Phone_Calls_Info__c> callMap){
        Map<String, Zoom_Phone_Calls_Info__c> orgCallsMap = new Map<String, Zoom_Phone_Calls_Info__c>();
        for (Zoom_Phone_Calls_Info__c calls : [SELECT z.Call_Id__c, z.id, Name, Call_Date_Time__c FROM Zoom_Phone_Calls_Info__c z WHERE CreatedDate = TODAY]) {
            orgCallsMap.put(calls.Call_Id__c, calls);
        }

        Map<String, Zoom_Phone_Calls_Info__c> resultMap = new Map<String, Zoom_Phone_Calls_Info__c>();
        for (String m : callMap.keySet()) {
            if (!orgCallsMap.containsKey(m)) resultMap.put(m, callMap.get(m));
        }

        List<Zoom_Phone_Calls_Info__c> resultCallsList = new List<Zoom_Phone_Calls_Info__c>();
        for (Zoom_Phone_Calls_Info__c i : resultMap.values()) {
            resultCallsList.add(i);
        }
        return resultCallsList;
    }
}