force-app/main/default/objects/Zoom_Phone_Calls_Info__c/Zoom_Phone_Calls_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Phone Calls Info</label>
    <nameField>
        <label>Zoom Phone Calls Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Phone Calls Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Zoom_Users_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Users_Info__c</fullName>
    <label>Zoom Users Info</label>
    <referenceTo>Zoom_Users_Info__c</referenceTo>
    <relationshipName>Zoom_Phone_Calls_Infos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/AHT_Inbound__c.field-meta.xml
<CustomField>
    <fullName>AHT_Inbound__c</fullName>
    <description>Average duration of inbound calls for Contact Center</description>
    <formula>TEXT(  MFLOOR( (Inbound_Calls_Duration__c  / Inbound_Calls__c) / 60))+&quot; min(s)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Average duration of inbound calls for Contact Center</inlineHelpText>
    <label>AHT Inbound CC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/AHT_Outbound__c.field-meta.xml
<CustomField>
    <fullName>AHT_Outbound__c</fullName>
    <description>Average outbound calls duration per day.</description>
    <formula>TEXT(  MFLOOR( (Outbound_Calls_Duration__c  / Outbound_Calls__c) / 60))+&quot; min(s)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Average outbound calls duration per day.</inlineHelpText>
    <label>AHT Outbound</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Available</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Away__c.field-meta.xml
<CustomField>
    <fullName>Away__c</fullName>
    <label>Away</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Do_Not_Disturb__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Disturb__c</fullName>
    <label>Do Not Disturb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Calendar_Event__c.field-meta.xml
<CustomField>
    <fullName>In_Calendar_Event__c</fullName>
    <label>In Calendar Event</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Meeting__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting__c</fullName>
    <label>In Meeting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/LogIn__c.field-meta.xml
<CustomField>
    <fullName>LogIn__c</fullName>
    <label>LogIn</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/LogOut__c.field-meta.xml
<CustomField>
    <fullName>LogOut__c</fullName>
    <label>LogOut</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline__c.field-meta.xml
<CustomField>
    <fullName>Offline__c</fullName>
    <label>Offline</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/On_Phone_Call__c.field-meta.xml
<CustomField>
    <fullName>On_Phone_Call__c</fullName>
    <label>On Phone Call</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <label>Presenting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Total_Inbound_Calls__c.field-meta.xml
<CustomField>
    <fullName>Total_Inbound_Calls__c</fullName>
    <label>Total Inbound Calls</label>
    <summaryFilterItems>
        <field>Zoom_Phone_Calls_Info__c.Inbound_Call__c</field>
        <operation>equals</operation>
        <value>inbound</value>
    </summaryFilterItems>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Total_Inbound_Calls_Duration__c.field-meta.xml
<CustomField>
    <fullName>Total_Inbound_Calls_Duration__c</fullName>
    <description>Total Inbound Calls Duration per day.</description>
    <inlineHelpText>Total Inbound Calls Duration per day.</inlineHelpText>
    <label>Total Inbound Calls Duration</label>
    <summarizedField>Zoom_Phone_Calls_Info__c.Inbound_Call_Duration__c</summarizedField>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Total_Outbound_Calls__c.field-meta.xml
<CustomField>
    <fullName>Total_Outbound_Calls__c</fullName>
    <description>Total Outbound phone calls</description>
    <inlineHelpText>Total Outbound phone calls</inlineHelpText>
    <label>Total Outbound Calls</label>
    <summaryFilterItems>
        <field>Zoom_Phone_Calls_Info__c.Outbound_Call__c</field>
        <operation>equals</operation>
        <value>outbound</value>
    </summaryFilterItems>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Total_Outbound_Calls_Duration__c.field-meta.xml
<CustomField>
    <fullName>Total_Outbound_Calls_Duration__c</fullName>
    <description>Total Outbound Calls Duration per day.</description>
    <inlineHelpText>Total Outbound Calls Duration per day.</inlineHelpText>
    <label>Total Outbound Calls Duration</label>
    <summarizedField>Zoom_Phone_Calls_Info__c.Outbound_Call_Duration__c</summarizedField>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Tracking_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Date__c</fullName>
    <label>Tracking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User_Log_In__c.field-meta.xml
<CustomField>
    <fullName>User_Log_In__c</fullName>
    <description>First user logged in</description>
    <label>User Log In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User_Log_Out__c.field-meta.xml
<CustomField>
    <fullName>User_Log_Out__c</fullName>
    <label>User Log Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_Phone_Calls_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Phone_Calls_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Phone Calls Info</label>
    <referenceTo>Zoom_Phone_Calls_Info__c</referenceTo>
    <relationshipLabel>Zoom Users Infos</relationshipLabel>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NEW/ZoomUsersInfoTriggerController.cls
public without sharing class ZoomUsersInfoTriggerController {
    public static void checkZoomUserInfoState(List<Zoom_Users_Info__c> newUsr, List<Zoom_Users_Info__c> oldUsr) {
        // System.debug('\n**************** oldUsr **************** \n'+ oldUsr);
        // System.debug('\n**************** newUsr **************** \n'+ newUsr);
        String statusOld = oldUsr[0].Presence_Status__c;
        String statusNew = newUsr[0].Presence_Status__c;
        // System.debug('\n**************** statusNew **************** \n'+ statusNew);
        // System.debug('\n**************** statusOld **************** \n'+ statusOld);
        if (statusOld != statusNew) {
            DateTime statusModifiedNew = newUsr[0].Status_Updated__c; // !!!!!!!!!!!!!!!! CHECK THIS
            DateTime statusModifiedOld = oldUsr[0].Status_Updated__c; // !!!!!!!!!!!!!!!! CHECK THIS
            Integer durationSeconds = Integer.valueOf((statusModifiedNew.getTime() - statusModifiedOld.getTime()) / (1000)); // in minutes
            // System.debug('\n**************** statusModifiedNew **************** \n'+ statusModifiedNew);
            // System.debug('\n**************** statusModifiedOld **************** \n'+ statusModifiedOld);
            // System.debug('\n**************** statusModifiedNew.getTime() **************** \n'+ statusModifiedNew.getTime());
            // System.debug('\n**************** statusModifiedOld.getTime() **************** \n'+ statusModifiedOld.getTime());
            // System.debug('\n**************** durationSeconds **************** \n'+ durationSeconds);
            updateZoomUserState(newUsr, durationSeconds, statusOld);
            checkFirstUserLogIn(statusOld, statusNew, newUsr, statusModifiedNew);
        }
    }

    public static void updateZoomUserState(List<Zoom_Users_Info__c> usr, Integer durationSeconds, String statusOld) {
        switch on statusOld {
            when 'Available' {
                // System.debug('######### Available ######### /n ');
                usr[0].Available__c += durationSeconds;
            }
            when 'Away' {
                // System.debug('######### Away ######### /n ');
                usr[0].Away__c += durationSeconds;
            }
            when 'In_Calendar_Event' {
                // System.debug('######### In_Calendar_Event ######### /n ');
                usr[0].In_Calendar_Event__c += durationSeconds;
            }
            when 'In_Meeting' {
                // System.debug('######### In_Meeting ######### /n ');
                usr[0].In_Meeting__c += durationSeconds;
            }
            when 'Offline' {
                // System.debug('######### Offline ######### /n ');
                usr[0].Offline__c += durationSeconds;
            }
            when 'On_Phone_Call' {
                // System.debug('######### On_Phone_Call ######### /n ');
                usr[0].On_Phone_Call__c += durationSeconds;
            }
            when 'Presenting' {
                // System.debug('######### Presenting ######### /n ');
                usr[0].Presenting__c += durationSeconds;
            }
            when 'Do_Not_Disturb' {
                // System.debug('######### Do_Not_Disturb ######### /n ');
                usr[0].Do_Not_Disturb__c += durationSeconds;
            }
        }
    }

    public static void checkFirstUserLogIn(String statusOld, String statusNew, List<Zoom_Users_Info__c> usr, DateTime statusModifiedNew) {
        if (statusOld == 'Initial' && (statusNew == 'Available' || statusNew == 'Away' || statusNew == 'On_Phone_Call' || statusNew == 'In_Meeting' || statusNew == 'Presenting' || statusNew == 'In_Calendar_Event')) {
            usr[0].User_Log_In__c = statusModifiedNew;
        }
    }
}

// oldUsr
// (Zoom_Users_Info__c:{Id=a4cDF0000006TbwYAE,
//      OwnerId=0051G000008D1IPQA0,
//      IsDeleted=false,
//      Name=Rebecca Unutoa,
//      CreatedDate=2023-01-05 19:04:12,
//      CreatedById=0051G000008D1IPQA0,
//      LastModifiedDate=2023-01-05 22:43:54,
//      LastModifiedById=005DF000007oUWBYA2,
//      SystemModstamp=2023-01-05 22:43:54,
//      LastActivityDate=null,
//      LastViewedDate=null,
//      LastReferencedDate=null,
//      ConnectionReceivedId=null,
//      ConnectionSentId=null,
//      User_Log_In__c=null,
//      User_Log_Out__c=null,
//      Available__c=40.00,
//      Away__c=0.00,
//      Offline__c=66.00,
//      Zoom_Phone_Calls_Info__c=null,
//      Email__c=runutoa@myubiquity.com,
//      Total_Inbound_Calls__c=9,
//      Tracking_Date__c=2023-01-05 00:00:00,
//      In_Meeting__c=0.00,
//      In_Calendar_Event__c=6.00,
//      Do_Not_Disturb__c=0.00,
//      On_Phone_Call__c=40.00,
//      Presence_Status__c=Available,
//      User__c=0051G0000076tPRQAY,
//      LogIn__c=null,
//      LogOut__c=null,
//      Presenting__c=0.00,
//      Status_Updated__c=2023-01-05 22:43:54,
//      Total_Outbound_Calls__c=2,
//      Total_Inbound_Calls_Duration__c=35,
//      Total_Outbound_Calls_Duration__c=11,
//      AHT_Inbound__c=3.89,
//      AHT_Outbound__c=5.50})

// newUsr
// (Zoom_Users_Info__c:{Id=a4cDF0000006TbwYAE,
//      OwnerId=0051G000008D1IPQA0,
//      IsDeleted=false,
//      Name=Rebecca Unutoa,
//      CreatedDate=2023-01-05 19:04:12,
//      CreatedById=0051G000008D1IPQA0,
//      LastModifiedDate=2023-01-05 22:43:54,
//      LastModifiedById=005DF000007oUWBYA2,
//      SystemModstamp=2023-01-05 22:43:54,
//      LastActivityDate=null,
//      LastViewedDate=null,
//      LastReferencedDate=null,
//      ConnectionReceivedId=null,
//      ConnectionSentId=null,
//      User_Log_In__c=null,
//      User_Log_Out__c=null,
//      Available__c=40.00,
//      Away__c=0.00,
//      Offline__c=66.00,
//      Zoom_Phone_Calls_Info__c=null,
//      Email__c=runutoa@myubiquity.com,
//      Total_Inbound_Calls__c=9,
//      Tracking_Date__c=2023-01-05 00:00:00,
//      In_Meeting__c=0.00,
//      In_Calendar_Event__c=6.00,
//      Do_Not_Disturb__c=0.00,
//      On_Phone_Call__c=40.00,
//      Presence_Status__c=On_Phone_Call,
//      User__c=0051G0000076tPRQAY,
//      LogIn__c=null,
//      LogOut__c=null,
//      Presenting__c=0.00,
//      Status_Updated__c=2023-01-05 22:44:46,
//      Total_Outbound_Calls__c=2,
//      Total_Inbound_Calls_Duration__c=35,
//      Total_Outbound_Calls_Duration__c=11,
//      AHT_Inbound__c=3.89,
//      AHT_Outbound__c=5.50})