force-app/main/default/objects/Zoom_Phone_Calls_Info__c/Zoom_Phone_Calls_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Phone Calls Info</label>
    <nameField>
        <label>Zoom Phone Calls Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Phone Calls Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Call_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Call_Date_Time__c</fullName>
    <description>Start time of the call</description>
    <inlineHelpText>Start time of the call</inlineHelpText>
    <label>Call Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Call_Id__c</fullName>
    <description>Unique identifier of the phone call.</description>
    <inlineHelpText>Unique identifier of the phone call.</inlineHelpText>
    <label>Call Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Hold_Time__c.field-meta.xml
<CustomField>
    <fullName>Hold_Time__c</fullName>
    <label>Hold Time</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Inbound_Call__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Call__c</fullName>
    <label>Inbound Call</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Inbound_Call_Duration__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Call_Duration__c</fullName>
    <label>Inbound Call Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Outbound_Call__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Call__c</fullName>
    <label>Outbound Call</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Outbound_Call_Duration__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Call_Duration__c</fullName>
    <label>Outbound Call Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Waiting_Time__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Time__c</fullName>
    <label>Waiting Time</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Zoom_Users_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Users_Info__c</fullName>
    <label>Zoom Users Info</label>
    <referenceTo>Zoom_Users_Info__c</referenceTo>
    <relationshipName>Zoom_Phone_Calls_Infos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Inbound_Calls__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Calls__c</fullName>
    <description>Total Number inbound Calls for Contact Center Users</description>
    <inlineHelpText>Total Number inbound Calls for Contact Center Users</inlineHelpText>
    <label>Inbound Calls CC</label>
    <summaryFilterItems>
        <field>Zoom_Phone_Calls_Info__c.Call_Direction__c</field>
        <operation>equals</operation>
        <value>inbound</value>
    </summaryFilterItems>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Outbound_Calls__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Calls__c</fullName>
    <description>Total Number of outbound Calls from Contact Center</description>
    <inlineHelpText>Total Number of outbound Calls from Contact Center</inlineHelpText>
    <label>Outbound Calls CC</label>
    <summaryFilterItems>
        <field>Zoom_Phone_Calls_Info__c.Call_Direction__c</field>
        <operation>equals</operation>
        <value>outbound</value>
    </summaryFilterItems>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Tracking_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Date__c</fullName>
    <label>Tracking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_Phone_Calls_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Phone_Calls_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Phone Calls Info</label>
    <referenceTo>Zoom_Phone_Calls_Info__c</referenceTo>
    <relationshipLabel>Zoom Users Infos</relationshipLabel>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OLD/ZoomUsersPhoneInfosBatch.cls
global with sharing class ZoomUsersPhoneInfosBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public static final String NOW = DateTime.now().format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
    public static final String LAST_30MIN = DateTime.now().addMinutes(-30).format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
    public static final Datetime LAST_30MINs = DateTime.now().addMinutes(-30);
    
    public String query = 'SELECT Id, Name, Email__c, Inbound_Calls__c, Outbound_Calls__c  FROM Zoom_Users_Info__c WHERE Tracking_Date__c = TODAY';
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Zoom_Users_Info__c> scope) {       
        List<Zoom_Phone_Calls_Info__c> callLst = new List<Zoom_Phone_Calls_Info__c>();
        Map<String, Zoom_Phone_Calls_Info__c> callMap = new Map<String, Zoom_Phone_Calls_Info__c>();
        Map<String, Zoom_Phone_Calls_Info__c> orgCallsMap  = new Map<String, Zoom_Phone_Calls_Info__c >();
        Map<String, Zoom_Phone_Calls_Info__c> resultMap = new Map<String, Zoom_Phone_Calls_Info__c>();

        for(Zoom_Phone_Calls_Info__c calls :[SELECT z.Call_Id__c, z.id, Name, CreatedDate,Call_Date_Time__c 
                                                FROM Zoom_Phone_Calls_Info__c z 
                                                WHERE CreatedDate = TODAY
                                            ]){ // CHECK > VARIABLE!!!!!!!!!!!!!! WHERE CreatedDate > :LAST_30MINs
            orgCallsMap.put(calls.Call_Id__c, calls);
        }
        for (Zoom_Users_Info__c usr : scope ){
            String endpoint = 'callout:ZoomPhone/phone/users/'+usr.email__c+'/call_logs';
            // String address = 'callout:ZoomPhone/phone/users/'+usr.email__c+'/call_logs';
            // String address = 'https://api.zoom.us/v2/ZoomPhone/phone/users/'+usr.email__c+'/call_logs';
            // String fromTime = '?from=' + '"' + LAST_30MIN + '"';
            // String toTime = '&to='  + '"' + NOW + '"';
            // // String pageSize = '&page_size=300';
            // String  = address + fromTime + toTime;

            HttpRequest req = new HttpRequest();
            req.setMethod('GET');
            req.setHeader('Content-type', 'application/json');
            req.setEndpoint(endpoint); 
            Http http = new Http();
            HttpResponse res = http.send(req);
            if (res.getStatusCode() == 200) {
                try{
                    ZooomUserResponseWrapper wrappedResponse = ZooomUserResponseWrapper.parse(res.getBody());
                    Integer inbound = 0;
                    Integer outbound = 0;
                    if(wrappedResponse.total_records != null && wrappedResponse.total_records != 0){
                        for(ZooomUserResponseWrapper.cls_call_logs val : wrappedResponse.call_logs){
                            Zoom_Phone_Calls_Info__c info = new Zoom_Phone_Calls_Info__c();
                            info.Name = usr.name;
                            info.Zoom_Users_Info__c = usr.id;
                            info.Email__c = usr.email__c;
                            info.Call_Date_Time__c = val.date_time;
                            info.Call_Id__c = val.call_id;
                            if(val.direction == 'inbound'){
                                inbound++;
                                info.Inbound_Call__c = val.direction;
                                info.Inbound_Call_Duration__c = val.duration/60; // CHECK !!!!
                                info.Waiting_Time__c = val.waiting_time; // ??CHECK
                                info.Hold_Time__c = val.hold_time; // ??CHECK
                            } else if(val.direction == 'outbound'){
                                outbound++;
                                info.Outbound_Call__c = val.direction;
                                info.Outbound_Call_Duration__c = val.duration;
                            }
                            // callLst.add(info);
                            callMap.put(info.Call_Id__c, info);
                            usr.Inbound_Calls__c = inbound;
                            usr.Outbound_Calls__c = outbound;
                        }
                }
                }  catch(Exception e) {
                    System.debug('Wrapper Exception may occurred ' +e.getMessage());
                }
            }
        }
        update scope;

        // //TODO: Create handler  and converter
        // Compare Maps with org data and inbound data
        for(String m: callMap.keySet()){
            if(!orgCallsMap.containsKey(m))
                resultMap.put(m, callMap.get(m));
        }
        // Convert to result list for insert
        for(Zoom_Phone_Calls_Info__c i: resultMap.values()){
            callLst.add(i);
        }
        insert callLst;
    } 
    global void finish(Database.BatchableContext BC){}
}

//Id batchJobId = Database.executeBatch(new ZoomUsersPhoneInfosBatch(), 10);

        // DateTime dt = DateTime.now();
        // String nowStr = String.valueOf(dt);
        // List<String> nowLst = nowStr.split(' ');
        // String now = String.join(nowLst,'\'T\'') + '\'Z\'';
        
        // DateTime dt15 = DateTime.now().addMinutes(-15);
        // String lstStr = String.valueOf(dt15);
        // List<String> lstStr15 = lstStr.split(' ');
        // String last15Min = String.join(lstStr15,'\'T\'') + '\'Z\'';