force-app/main/default/objects/Zoom_Phone_Calls_Info__c/Zoom_Phone_Calls_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Phone Calls Info</label>
    <nameField>
        <label>Zoom Phone Calls Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Phone Calls Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <description>Result of the call</description>
    <inlineHelpText>Result of the call</inlineHelpText>
    <label>Call Result</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Phone_Calls_Info__c/fields/Zoom_Users_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Users_Info__c</fullName>
    <label>Zoom Users Info</label>
    <referenceTo>Zoom_Users_Info__c</referenceTo>
    <relationshipName>Zoom_Phone_Calls_Infos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_Phone_Calls_Info__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Phone_Calls_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Phone Calls Info</label>
    <referenceTo>Zoom_Phone_Calls_Info__c</referenceTo>
    <relationshipLabel>Zoom Users Infos</relationshipLabel>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZoomUsersPhoneInfosBatchHttpCalloutMock.cls
@isTest
public class ZoomUsersPhoneInfosBatchHttpCalloutMock implements HttpCalloutMock{
    @TestSetup
    public static void makeData(){
        List<Zoom_Users_Info__c> zoomUsers = ZoomTestDataFactory.createListZoomUsersInfo(3, 'System Administrator', '@myubiquity.com');
    }

    public HTTPResponse respond(HTTPRequest request) {
        DateTime now = DateTime.now();
        String nowString = now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('{"total_records":2,"call_logs":[{"call_id":"123","Email":"testuser0@myubiquity.com", "caller_name":"John Smith","caller_number":"555-555-5555","date_time":"' + nowString + '","direction":"inbound","duration":60,"result":"Auto Recorded","recording_id":"e0220382054f4d8882127bc3e50c48c1","recording_type":"mp4"},{"call_id":"456","Email":"testuser1@myubiquity.com","caller_name":"Jane Doe","caller_number":"555-555-5556","date_time":"' + nowString + '","direction":"outbound","duration":90,"result":"Call connected"}]}');
        response.setStatusCode(200);
        return response; 
    }

    @isTest
    public static void testBatch() {
        Test.setMock(HttpCalloutMock.class, new ZoomUsersPhoneInfosBatchHttpCalloutMock());
        Test.startTest();
        Database.executeBatch(new ZoomUsersPhoneInfosBatch());
        Test.stopTest();
        List<Zoom_Phone_Calls_Info__c> calls = [SELECT Name, Zoom_Users_Info__c, Email__c, Call_Result__c FROM Zoom_Phone_Calls_Info__c WHERE Email__c LIKE :'%testuser%'];
        System.assertEquals(2, calls.size(), 'Should create 2 phone call records');
    }

    @isTest
    public static void testScheduler(){
        Test.setMock(HttpCalloutMock.class, new ZoomUsersPhoneInfosBatchHttpCalloutMock());
        Test.startTest();
        ZoomUsersPhoneInfosBatch.start(007);
        ZoomUsersPhoneInfosBatch.start(0);
        Test.stopTest();
        List<Zoom_Phone_Calls_Info__c> calls = [SELECT Name, Zoom_Users_Info__c, Email__c, Call_Result__c FROM Zoom_Phone_Calls_Info__c WHERE Email__c LIKE :'%testuser%'];
        System.assertEquals(2, calls.size(), 'Should create 2 phone call records'); 
    }
}