force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Available</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Away__c.field-meta.xml
<CustomField>
    <fullName>Away__c</fullName>
    <label>Away</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Call_Center_Member__c.field-meta.xml
<CustomField>
    <fullName>Call_Center_Member__c</fullName>
    <description>Call Center member</description>
    <inlineHelpText>Call Center member</inlineHelpText>
    <label>Call Center Member</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Do_Not_Disturb__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Disturb__c</fullName>
    <label>Do Not Disturb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Extension_Id__c.field-meta.xml
<CustomField>
    <fullName>Extension_Id__c</fullName>
    <description>Zoom application extension Id.</description>
    <inlineHelpText>Zoom application extension Id.</inlineHelpText>
    <label>Extension Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Extension_Number__c.field-meta.xml
<CustomField>
    <fullName>Extension_Number__c</fullName>
    <description>Zoom application extension number.</description>
    <inlineHelpText>Zoom application extension number.</inlineHelpText>
    <label>Extension Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Calendar_Event__c.field-meta.xml
<CustomField>
    <fullName>In_Calendar_Event__c</fullName>
    <label>In Calendar Event</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Meeting__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting__c</fullName>
    <label>In Meeting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline__c.field-meta.xml
<CustomField>
    <fullName>Offline__c</fullName>
    <label>Offline</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/On_Phone_Call__c.field-meta.xml
<CustomField>
    <fullName>On_Phone_Call__c</fullName>
    <label>On Phone Call</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <label>Presenting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Tracking_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Date__c</fullName>
    <label>Tracking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_Department__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Department__c</fullName>
    <label>Zoom Department</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_Email__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Email__c</fullName>
    <description>Zoom application email address.</description>
    <inlineHelpText>Zoom application email address.</inlineHelpText>
    <label>Zoom Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_User_Id__c</fullName>
    <description>The unique identifier of the user (userId).</description>
    <inlineHelpText>The unique identifier of the user (userId).</inlineHelpText>
    <label>Zoom User Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZoomUserInfosRecordCreatorBatch/ZoomUserInfosRecordCreatorBatch.cls
public with sharing class ZoomUserInfosRecordCreatorBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, schedulable {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // NOTE: Retrieve Active users from org
        String query = 'SELECT Id, Name, Email, CallCenterId FROM User WHERE isActive = true AND CallCenterId != null';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<User> scope) {
        List<Zoom_Users_Info__c> result = new List<Zoom_Users_Info__c>();
        Map<Id, CallCenter> mapCallCenterIdName = new Map<Id, CallCenter>([SELECT Id, Name FROM CallCenter]);
        Map<String, ZoomUserInfosRecordCreatorBatchEntity.UsersProfWrapper> emailToZoomUsersProfileMap = ZoomUserInfosRecordCreatorBatchService.getMapUsersProfiles();

        // TODO: Refactor this to separet method
        Id recordTypePhoneId = Schema.SObjectType.Zoom_Users_Info__c.getRecordTypeInfosByName().get('Zoom Phone').getRecordTypeId();
        Id recordTypeCallCenterId = Schema.SObjectType.Zoom_Users_Info__c.getRecordTypeInfosByName().get('Contact Center').getRecordTypeId();
        

        for (User u : scope) {
            Zoom_Users_Info__c zoomUser = new Zoom_Users_Info__c();
            String emailKey = u.Email.substringBefore('.invalid').toLowerCase().trim();
            ZoomUserInfosRecordCreatorBatchEntity.UsersProfWrapper userInfo = emailToZoomUsersProfileMap.get(emailKey);
            String callCenterName = mapCallCenterIdName.get(u.CallCenterId).Name;

            zoomUser.User__c = u.id;
            zoomUser.Email__c = u.Email.substringBefore('.invalid');// NOTE: substring used for devorg!!!
            // zoomUser.Email__c = u.Email;
            zoomUser.Name                     = u.Name;
            zoomUser.OwnerId                  = u.id;
            zoomUser.Presence_Status__c       = 'Initial';
            zoomUser.Status_Updated__c        = Datetime.Now();
            zoomUser.Tracking_Date__c         = Date.today();
            zoomUser.Available__c             = 0;
            zoomUser.Away__c                  = 0;
            zoomUser.In_Calendar_Event__c     = 0;
            zoomUser.In_Meeting__c            = 0;
            zoomUser.Offline__c               = 0;
            zoomUser.On_Phone_Call__c         = 0;
            zoomUser.Presenting__c            = 0;
            zoomUser.Do_Not_Disturb__c        = 0;
            zoomUser.Call_Center_Member__c    = callCenterName;
            zoomUser.RecordTypeId             = callCenterName == 'Zoom Phone Call Center' ? recordTypePhoneId : recordTypeCallCenterId; // TODO: Refactor this to separet method

            if (userInfo != null) {
                zoomUser.Zoom_User_Id__c = userInfo.id;
                zoomUser.Zoom_Department__c = userInfo.department;
                zoomUser.Zoom_Email__c = userInfo.email;
                zoomUser.Extension_Id__c = userInfo.extension_id;
                zoomUser.Extension_Number__c = userInfo.extension_number;
            }
            result.add(zoomUser);
        }
        insert result;
    }
    public void finish(Database.BatchableContext bc) {
    }

    //NOTE: Schedule interface
    public static void start(Integer hour) {
        string jobName = 'Zoom Users Info Create Records';
        if (hour == 7)
            Database.executeBatch(new ZoomUserInfosRecordCreatorBatch(), 50);
        else {
            jobName = jobName += ' - ' + datetime.now().format();
            String cron = '0 0 ' + String.valueof(hour) + ' ? * MON-FRI'; // NOTE: Execute From Monday - Friday
            system.schedule(jobName, cron, new ZoomUserInfosRecordCreatorBatch());
        }
    }

    public void execute(SchedulableContext SC) {
        Database.executeBatch(new ZoomUserInfosRecordCreatorBatch(), 50);
    }
}
// EXECUTE SCHEDULE
// immediately submits the batch job - 007 param just a JOKE!!!
//ZoomUserInfosRecordCreatorBatch.start(007);

// schedules the batch job to run nightly at 0am. - FROM 0 to 23
// ZoomUserInfosRecordCreatorBatch.start(0);