force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Available</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Away__c.field-meta.xml
<CustomField>
    <fullName>Away__c</fullName>
    <label>Away</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/CC_Prev_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Prev_Status__c</fullName>
    <label>Prev Status CC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/CC_Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>CC_Status_Updated__c</fullName>
    <label>Status Updated CC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Contact_Center_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Center_Status__c</fullName>
    <description>Contact center user&apos;s availability status.</description>
    <inlineHelpText>Contact center user&apos;s availability status.</inlineHelpText>
    <label>Status CC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Do_Not_Disturb__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Disturb__c</fullName>
    <label>Do Not Disturb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Calendar_Event__c.field-meta.xml
<CustomField>
    <fullName>In_Calendar_Event__c</fullName>
    <label>In Calendar Event</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Meeting__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting__c</fullName>
    <label>In Meeting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Not_Ready__c.field-meta.xml
<CustomField>
    <fullName>Not_Ready__c</fullName>
    <label>Not Ready</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Occupied__c.field-meta.xml
<CustomField>
    <fullName>Occupied__c</fullName>
    <label>Occupied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline__c.field-meta.xml
<CustomField>
    <fullName>Offline__c</fullName>
    <label>Offline</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline_Status__c.field-meta.xml
<CustomField>
    <fullName>Offline_Status__c</fullName>
    <label>Offline Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/On_Phone_Call__c.field-meta.xml
<CustomField>
    <fullName>On_Phone_Call__c</fullName>
    <label>On Phone Call</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <label>Presenting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Ready__c.field-meta.xml
<CustomField>
    <fullName>Ready__c</fullName>
    <label>Ready</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Tracking_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Date__c</fullName>
    <label>Tracking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Zoom_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_User_Id__c</fullName>
    <description>The unique identifier of the user (userId).</description>
    <inlineHelpText>The unique identifier of the user (userId).</inlineHelpText>
    <label>Zoom User Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/recordTypes/Contact_Center.recordType-meta.xml
<RecordType>
    <fullName>Contact_Center</fullName>
    <active>true</active>
    <description>Record type for users  from Zoom Contact Center</description>
    <label>Contact Center</label>
</RecordType>

force-app/main/default/classes/TestClasses/ZoomWebhookControllerTest.cls
@isTest
public class ZoomWebhookControllerTest {

    @TestSetup
    static void makeData(){
        CallCenter cc =[SELECT Id FROM CallCenter LIMIT 1];
        Profile profId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User usr = new User();
        usr.Email                           = 'testzoommail23@mail.com';
        usr.Username                        = 'testzoommail23@mail.com';
        usr.FirstName                       = 'Test';
        usr.LastName                        = 'User';
        usr.Alias                           = 'tuser';
        usr.TimeZoneSidKey                  = 'America/Los_Angeles';
        usr.LocaleSidKey                    = 'en_US';
        usr.EmailEncodingKey                = 'UTF-8';
        usr.LanguageLocaleKey               = 'en_US';
        usr.isActive                        = true;
        usr.ProfileId                       = profId.Id;
        usr.CallCenterId                    = cc.Id;
        insert usr;

        User createdUser = [SELECT Id, Email, Name FROM User WHERE Username = 'testzoommail23@mail.com' LIMIT 1];

        Zoom_Users_Info__c zoomUser = new Zoom_Users_Info__c();
        zoomUser.User__c                    = createdUser.Id;
        zoomUser.Email__c                   = createdUser.Email;
        zoomUser.Name                       = createdUser.Name;
        zoomUser.Presence_Status__c         = 'Away';
        zoomUser.Status_Updated__c          = DateTime.now();
        zoomUser.Tracking_Date__c           = Date.today();
        zoomUser.Available__c               = 0;
        zoomUser.Away__c                    = 0;
        zoomUser.In_Calendar_Event__c       = 0;
        zoomUser.In_Meeting__c              = 0;
        zoomUser.Offline__c                 = 0;
        zoomUser.On_Phone_Call__c           = 0;
        zoomUser.Presenting__c              = 0;
        zoomUser.Do_Not_Disturb__c          = 0;
        zoomUser.Zoom_User_Id__c            = 'kJdQOXj6TXeWcSfh_ysPVQ';
        zoomUser.Contact_Center_Status__c   = 'Ready';
        zoomUser.CC_Prev_Status__c          = 'Occupied';
        zoomUser.CC_Status_Updated__c       = DateTime.Now();
        zoomUser.Ready__c                   = 0;
        zoomUser.Not_Ready__c               = 0;
        zoomUser.Occupied__c                = 0;
        zoomUser.Offline_Status__c          = 0;
        insert zoomUser;
}

    @isTest
    public static void checkZoomEventTest(){
        String statusBody = '{"event":"user.presence_status_updated","payload":{"account_id":"kJdQOXj6TXeWcSfh_ysPVQ","object":{"date_time":"2023-01-24T14:47:36Z","email":"testzoommail23@mail.com","id":"p3x1bwrmsh6tnl_bxyrlca","presence_status":"On_Phone_Call"}},"event_ts":1674571656505}';

        String loginBody = '{"event":"user.signed_in","payload":{"account_id":"kJdQOXj6TXeWcSfh_ysPVQ","object":{"date_time":"2023-01-24T14:47:36Z","email":"testzoommail23@mail.com","id":"p3x1bwrmsh6tnl_bxyrlca","presence_status":"Available"}},"event_ts":1674571656505}';

        String logoutBody = '{"event":"user.signed_out","payload":{"account_id":"kJdQOXj6TXeWcSfh_ysPVQ","object":{"date_time":"2023-01-24T14:47:36Z","email":"testzoommail23@mail.com","id":"p3x1bwrmsh6tnl_bxyrlca","presence_status":"Offline"}},"event_ts":1674571656505}';

        String ccLoginBody = '{ "event": "contact_center.user_login", "event_ts": 1627906944384, "payload": { "account_id": "D8cJuqWVQ623CI4Q8yQK0Q", "object": { "user_id": "ukAAkZKfROKMSw1bj_RDFQ", "display_name": "Jill Chill", "user_email": "testzoommail23@mail.com", "date_time": "2022-02-15T09:27:15Z"}}}';

        String ccLogoutBody = '{"event": "contact_center.user_logout","event_ts": 1627906944384,"payload": {"account_id": "D8cJuqWVQ623CI4Q8yQK0Q","object": {"user_id": "ukAAkZKfROKMSw1bj_RDFQ","display_name": "Jill Chill","user_email": "testzoommail23@mail.com","date_time": "2022-02-15T09:27:15Z"}}}';

        String ccStatusBody = '{"event": "contact_center.user_status_changed","event_ts": 1627906944384,"payload": {"account_id": "D8cJuqWVQ623CI4Q8yQK0Q","object": {"user_id": "ukAAkZKfROKMSw1bj_RDFQ","display_name": "Jill Chill","user_email": "testzoommail23@mail.com","previous_status_id": "2","previous_status_name": "Not Ready","previous_sub_status_id": "20","previous_sub_status_name": "Break","current_status_id": "2","current_status_name": "Not Ready","current_sub_status_id": "21","current_sub_status_name": "Meal","date_time": "2022-02-15T09:27:15Z"}}}';

        Map<String,Object> respMapstatus    = (Map<String,Object>)JSON.deserializeUntyped(statusBody);
        Map<String,Object> respMaplogin     = (Map<String,Object>)JSON.deserializeUntyped(loginBody);
        Map<String,Object> respMaplogout    = (Map<String,Object>)JSON.deserializeUntyped(logoutBody);
        Map<String,Object> respMapccLogin   = (Map<String,Object>)JSON.deserializeUntyped(ccLoginBody);
        Map<String,Object> respMapccLogout  = (Map<String,Object>)JSON.deserializeUntyped(ccLogoutBody);
        Map<String,Object> respMapccStatus  = (Map<String,Object>)JSON.deserializeUntyped(ccStatusBody);
        Test.startTest();
            ZoomWebhookController.checkZoomEvent(respMapstatus);
            ZoomWebhookController.checkZoomEvent(respMaplogin);
            ZoomWebhookController.checkZoomEvent(respMaplogout);
            ZoomWebhookController.checkZoomEvent(respMapccLogin);
            ZoomWebhookController.checkZoomEvent(respMapccLogout);
            ZoomWebhookController.checkZoomEvent(respMapccStatus);
        Test.stopTest();
        Zoom_Users_Info__c u = [SELECT Presence_Status__c FROM Zoom_Users_Info__c WHERE Email__c = 'testzoommail23@mail.com'];
        System.assertEquals('Offline', u.presence_status__c, 'Presence status should be Offline');
    }
}