force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Available</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Away__c.field-meta.xml
<CustomField>
    <fullName>Away__c</fullName>
    <label>Away</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/CC_Prev_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Prev_Status__c</fullName>
    <label>Prev Status CC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/CC_Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>CC_Status_Updated__c</fullName>
    <label>Status Updated CC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Contact_Center_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Center_Status__c</fullName>
    <description>Contact center user&apos;s availability status.</description>
    <inlineHelpText>Contact center user&apos;s availability status.</inlineHelpText>
    <label>Status CC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Custom_CC_Status__c.field-meta.xml
<CustomField>
    <fullName>Custom_CC_Status__c</fullName>
    <label>Custom CC Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Custom_Status__c.field-meta.xml
<CustomField>
    <fullName>Custom_Status__c</fullName>
    <label>Custom Status</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Do_Not_Disturb__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Disturb__c</fullName>
    <label>Do Not Disturb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Calendar_Event__c.field-meta.xml
<CustomField>
    <fullName>In_Calendar_Event__c</fullName>
    <label>In Calendar Event</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Meeting__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting__c</fullName>
    <label>In Meeting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Not_Ready__c.field-meta.xml
<CustomField>
    <fullName>Not_Ready__c</fullName>
    <label>Not Ready</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Occupied__c.field-meta.xml
<CustomField>
    <fullName>Occupied__c</fullName>
    <label>Occupied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline__c.field-meta.xml
<CustomField>
    <fullName>Offline__c</fullName>
    <label>Offline</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline_Status__c.field-meta.xml
<CustomField>
    <fullName>Offline_Status__c</fullName>
    <label>Offline Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/On_Phone_Call__c.field-meta.xml
<CustomField>
    <fullName>On_Phone_Call__c</fullName>
    <label>On Phone Call</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <label>Presenting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Ready__c.field-meta.xml
<CustomField>
    <fullName>Ready__c</fullName>
    <label>Ready</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ZoomTrigger/ZoomUsersInfoTriggerController.cls
public without sharing class ZoomUsersInfoTriggerController {
	public static void checkZoomUserInfoState(List<Zoom_Users_Info__c> newUsr, List<Zoom_Users_Info__c> oldUsr) {
		DateTime nowGMT = DateTime.now();
		DateTime nowPST = nowGMT.addHours(-8);
		Boolean isWorkingHours = !Test.isRunningTest() ? nowPST.hour() >= 5 && nowPST.hour() <= 18 : true;

		DateTime statusModifiedNew 	= newUsr[0].Status_Updated__c;
		DateTime statusModifiedOld 	= oldUsr[0].Status_Updated__c;
		Integer durationSeconds 	= Integer.valueOf((statusModifiedNew.getTime() - statusModifiedOld.getTime()) / (1000));

		String statusOld 			= oldUsr[0].Presence_Status__c;
		String statusNew 			= newUsr[0].Presence_Status__c;

		DateTime ccStatusModifiedNew 	= newUsr[0].CC_Status_Updated__c;
		DateTime ccStatusModifiedOld 	= oldUsr[0].CC_Status_Updated__c;
		Integer ccDurationSeconds 	= Integer.valueOf((ccStatusModifiedNew.getTime() - ccStatusModifiedOld.getTime()) / (1000));
		String contCenterCurrentStatus 	= newUsr[0].Contact_Center_Status__c;
		String contCenterPreviousStatus = newUsr[0].CC_Prev_Status__c;

		if (isWorkingHours) {
			if (statusOld != statusNew) {
				updateZoomUserState(newUsr[0], durationSeconds, statusOld);
			}
			if (contCenterCurrentStatus != contCenterPreviousStatus) {
				updateContactCenterState(newUsr[0], ccDurationSeconds, contCenterPreviousStatus);
			}
		}
	}

	public static void updateZoomUserState(Zoom_Users_Info__c usr, Integer durationSeconds, String statusOld) {
		switch on statusOld {
			when 'Available' {
				usr.Available__c += durationSeconds;
			}
			when 'Away' {
				usr.Away__c += durationSeconds;
			}
			when 'In_Calendar_Event' {
				usr.In_Calendar_Event__c += durationSeconds;
			}
			when 'In_Meeting' {
				usr.In_Meeting__c += durationSeconds;
			}
			when 'Offline' {
				usr.Offline__c += durationSeconds;
			}
			when 'On_Phone_Call' {
				usr.On_Phone_Call__c += durationSeconds;
			}
			when 'Presenting' {
				usr.Presenting__c += durationSeconds;
			}
			when 'Do_Not_Disturb' {
				usr.Do_Not_Disturb__c += durationSeconds;
			}
		}
	}

	public static void updateContactCenterState(Zoom_Users_Info__c usr, Integer ccDurationSeconds, String previousStatus) {
		switch on previousStatus {
			when 'Ready' {
				usr.Ready__c += ccDurationSeconds;
			}
			when 'Not Ready' {
				usr.Not_Ready__c += ccDurationSeconds;
			}
			when 'Occupied' {
				usr.Occupied__c += ccDurationSeconds;
			}
			when 'Offline' {
				usr.Offline_Status__c += ccDurationSeconds;
			}
		}
	}
}

//  Available__c, Away__c, In_Calendar_Event__c, In_Meeting__c, Offline__c, On_Phone_Call__c, Presenting__c, Do_Not_Disturb__c, Custom_Status__c, Ready__c, Not_Ready__c, Occupied__c, Offline_Status__c, Custom_CC_Status__c