force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ZoomTrigger/ZoomUsersInfoTriggerControllerTest.cls
@isTest
private class ZoomUsersInfoTriggerControllerTest {

    @isTest
    private static void zoomUsersTriggerTestMethod(){
        List<Zoom_Users_Info__c> lstUsr = ZoomTestDataFactory.createListZoomUsersInfo(8, 'System Administrator', 'test@myubiquity.com');
        List<String> statuses = new List<String>{'Do_Not_Disturb','Available', 'Away', 'In_Calendar_Event', 'In_Meeting', 'Offline', 'On_Phone_Call', 'Presenting'};

        Test.startTest();
        for(Integer i=0; i<statuses.size(); i++){
            lstUsr[i].Presence_Status__c = statuses[i];
            lstUsr[i].Status_Updated__c = DateTime.now().addHours(1);
            update lstUsr[i];
        }
        Test.stopTest();   
        System.assertEquals(8, lstUsr.size(), '8 Zoom Users Info records should be created');     
    }
}