force-app/main/default/objects/Zoom_Users_Info__c/Zoom_Users_Info__c.object-meta.xml
<CustomObject>
    <label>Zoom Users</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Users Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <label>Available</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Away__c.field-meta.xml
<CustomField>
    <fullName>Away__c</fullName>
    <label>Away</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Do_Not_Disturb__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Disturb__c</fullName>
    <label>Do Not Disturb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Calendar_Event__c.field-meta.xml
<CustomField>
    <fullName>In_Calendar_Event__c</fullName>
    <label>In Calendar Event</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/In_Meeting__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting__c</fullName>
    <label>In Meeting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Inbound_Calls__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Calls__c</fullName>
    <description>Total Number inbound Calls for Contact Center Users</description>
    <inlineHelpText>Total Number inbound Calls for Contact Center Users</inlineHelpText>
    <label>Inbound Calls CC</label>
    <summaryFilterItems>
        <field>Zoom_Phone_Calls_Info__c.Call_Direction__c</field>
        <operation>equals</operation>
        <value>inbound</value>
    </summaryFilterItems>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/LogIn__c.field-meta.xml
<CustomField>
    <fullName>LogIn__c</fullName>
    <label>LogIn</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/LogOut__c.field-meta.xml
<CustomField>
    <fullName>LogOut__c</fullName>
    <label>LogOut</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Offline__c.field-meta.xml
<CustomField>
    <fullName>Offline__c</fullName>
    <label>Offline</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/On_Phone_Call__c.field-meta.xml
<CustomField>
    <fullName>On_Phone_Call__c</fullName>
    <label>On Phone Call</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Outbound_Calls__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Calls__c</fullName>
    <description>Total Number of outbound Calls from Contact Center</description>
    <inlineHelpText>Total Number of outbound Calls from Contact Center</inlineHelpText>
    <label>Outbound Calls CC</label>
    <summaryFilterItems>
        <field>Zoom_Phone_Calls_Info__c.Call_Direction__c</field>
        <operation>equals</operation>
        <value>outbound</value>
    </summaryFilterItems>
    <summaryForeignKey>Zoom_Phone_Calls_Info__c.Zoom_Users_Info__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presence_Status__c.field-meta.xml
<CustomField>
    <fullName>Presence_Status__c</fullName>
    <description>User status for Zoom App</description>
    <inlineHelpText>User status for Zoom App</inlineHelpText>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <label>Presenting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <label>Status Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/Tracking_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Date__c</fullName>
    <label>Tracking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zoom_Users_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User_Log_In__c.field-meta.xml
<CustomField>
    <fullName>User_Log_In__c</fullName>
    <description>First user logged in</description>
    <label>User Log In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zoom_Users_Info__c/fields/User_Log_Out__c.field-meta.xml
<CustomField>
    <fullName>User_Log_Out__c</fullName>
    <label>User Log Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ZoomUsersInfoTriggerController.cls
public without sharing class ZoomUsersInfoTriggerController {
    public static void checkZoomUserInfoState(List<Zoom_Users_Info__c> newUsr, List<Zoom_Users_Info__c> oldUsr ){
        System.debug('****************oldUsr**************** '+ oldUsr);
        System.debug('****************newUsr**************** '+ newUsr);
        String stateOld = oldUsr[0].Presence_Status__c;
        String stateNew = newUsr[0].Presence_Status__c;
        if(stateOld != stateNew){
            DateTime modifiedNew = newUsr[0].Status_Updated__c;
            DateTime modifiedOld = oldUsr[0] == null ? DateTime.now() : oldUsr[0].Status_Updated__c;
            Decimal durationSeconds = Integer.valueOf((modifiedNew.getTime() - modifiedOld.getTime())/(60000));
            System.debug('****************modifiedNew**************** '+ modifiedNew);
            System.debug('****************modifiedOld**************** '+ modifiedOld);
            System.debug('****************durationSeconds**************** '+ durationSeconds);
            updateZoomUserState(newUsr, durationSeconds, stateOld);
        }
        System.debug('****************stateNew**************** '+ stateNew);
        System.debug('****************stateOld**************** '+ stateOld);

    }


    public static void updateZoomUserState(List<Zoom_Users_Info__c> usr, Decimal durationSeconds, String stateOld){
        switch on stateOld {
            when 'Available' {
                System.debug('######### Available ######### /n ');
                usr[0].Available__c += durationSeconds;
            }
            when 'Away' {
                System.debug('######### Away ######### /n ');
                usr[0].Away__c += durationSeconds;
            }
            when 'In_Calendar_Event' {
                System.debug('######### In_Calendar_Event ######### /n ');
                usr[0].In_Calendar_Event__c += durationSeconds;
            }
            when 'In_Meeting' {
                System.debug('######### In_Meeting ######### /n ');
                usr[0].In_Meeting__c += durationSeconds;
            }
            when 'Offline' {
                System.debug('######### Offline ######### /n ');
                usr[0].Offline__c += durationSeconds;
            }
            when 'On_Phone_Call' {
                System.debug('######### On_Phone_Call ######### /n ');
                usr[0].On_Phone_Call__c += durationSeconds;
            }
            when 'Presenting' {
                System.debug('######### Presenting ######### /n ');
                usr[0].Presenting__c += durationSeconds;
            }
            when 'Do_Not_Disturb' {
                System.debug('######### Do_Not_Disturb ######### /n ');
                usr[0].Do_Not_Disturb__c += durationSeconds;
            }
        } 
    }
}




// (Zoom_Users_Info__c:
// {Id=a4cDF0000006Rw9YAE,
//     OwnerId=0051G000008D1IPQA0,
//     IsDeleted=false,
//     Name=Krystal Burgess,
//     CreatedDate=2022-12-27 08:00:11,
//     CreatedById=0051G000008D1IPQA0,
//     LastModifiedDate=2022-12-27 20:15:27,
//     LastModifiedById=005DF000007oUWBYA2,
//     SystemModstamp=2022-12-27 20:15:27,
//     LastActivityDate=null,
//     LastViewedDate=null,
//     LastReferencedDate=null,
//     User_Log_In__c=null,
//     User_Log_Out__c=null,
//     Available__c=null,
//     Away__c=null,
//     Offline__c=null,
//     Email__c=kburgess@myubiquity.com,
//     Tracking_Date__c=2022-12-27 00:00:00,
//     In_Meeting__c=null,
//     In_Calendar_Event__c=null,
//     Do_Not_Disturb__c=null,
//     On_Phone_Call__c=null,
//     Presence_Status__c=Available,
//     Inbound_Calls__c=5,
//     Outbound_Calls__c=1,
//     User__c=00537000003l1LCAAY,
//     LogIn__c=2022-12-27 18:43:27,
//     LogOut__c=2022-12-27 18:34:16
// })